apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-config
          mountPath: "/etc/apache2/sites-available/000-default.conf"
          subPath: "000-default.conf"
          readOnly: true
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-config
          mountPath: "/etc/apache2/certificates/cert.pem"
          subPath: "cert.pem"
          readOnly: true
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-config
          mountPath: "/etc/apache2/certificates/key.pem"
          subPath: "key.pem"
          readOnly: true
      volumes:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-config
        configMap:
          name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
          items:
          - key: "000-default.conf"
            path: "000-default.conf"
          - key: "cert.pem"
            path: "cert.pem"
          - key: "key.pem"
            path: "key.pem"
